<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb244412b3556d6140e18fb2fe9d68b09
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Phpml\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Phpml\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-ai/php-ml/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb244412b3556d6140e18fb2fe9d68b09::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb244412b3556d6140e18fb2fe9d68b09::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb244412b3556d6140e18fb2fe9d68b09::$classMap;

        }, null, ClassLoader::class);
    }
}
